# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171123_1252'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agenda',
            table=None,
        ),
    ]
