# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171123_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='img_path',
            field=models.CharField(default='/static/img/blog/default.jpg', max_length=256),
        ),
    ]
