# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171123_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='body',
            field=models.TextField(),
        ),
    ]
