# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171123_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('recommender', models.CharField(max_length=128)),
                ('reason', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
