# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_applicant_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 20, 25, 12, 64405, tzinfo=utc)),
        ),
    ]
