# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171124_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2017, 11, 24, 8, 36, 11, 231869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='time',
            field=models.TimeField(verbose_name=datetime.datetime(2017, 11, 24, 8, 36, 11, 231890, tzinfo=utc)),
        ),
    ]
