# Generated by Django 2.0.3 on 2018-03-10 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171124_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 3, 10, 6, 54, 11, 15666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='time',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 3, 10, 6, 54, 11, 15685, tzinfo=utc)),
        ),
    ]
