# Generated by Django 2.0.3 on 2018-03-10 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180310_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 3, 10, 8, 25, 28, 967002, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='time',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 3, 10, 8, 25, 28, 967039, tzinfo=utc)),
        ),
    ]
