# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180310_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2018, 3, 10, 18, 15, 45, 705849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='time',
            field=models.TimeField(verbose_name=datetime.datetime(2018, 3, 10, 18, 15, 45, 705891, tzinfo=utc)),
        ),
    ]
